###
# Jekyll Configuration
###
pygments: true
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title
exclude:
  - assets
  - gruntfile.js
  - package.json

###
# Site Configuration
###
domain: pspeter3.com
title: pspeter3
author: Phips Peter
description: Hacker and Sailor

###
# Navigation
###
accounts:
  -
    name: RSS
    service: rss
    url: http://pspeter3.com/rss.xml
  -
    service: github
    url: http://www.github.com/pspeter3
  -
    service: twitter
    url: http://www.twitter.com/pspeter3
  -
    name: LinkedIn
    service: linkedin
    url: http://www.linkedin.com/in/pspeter3
  -
    service: instagram
    url: http://instagram.com/pspeter3
  -
    name: App.net
    service: adn
    url: https://alpha.app.net/pspeter3

###
# Analytics
###
analytics:
  google: UA-42476212-1
  mixpanel: 2b7c1f7daaab155dbae324f1ced06122
