###
# Jekyll Configuration
###
pygments: true
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title
exclude:
  - assets

###
# Site Configuration
###
title: pspeter3
author: Phips Peter
description: Hacker and Sailor

###
# Social Accounts
###
accounts:
  twitter: pspeter3
  github: pspeter3